/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/dice.glb
*/

import { useGLTF } from "@react-three/drei"

export function Model(props) {
	const { nodes, materials } = useGLTF("/dice.glb")
	return (
		<group {...props} dispose={null}>
			<group position={[0, 1, 0]}>
				<mesh
					geometry={nodes.Cube_1.geometry}
					material={materials.black}
				/>
				<mesh
					geometry={nodes.Cube_2.geometry}
					material={materials.white}
				/>
			</group>
		</group>
	)
}

useGLTF.preload("/dice.glb")
